---
kind: pipeline
name: default

steps:
- name: build
  image: golang:latest
  pull: always
  commands:
  - make
  environment:
    GO111MODULE: "on"

- name: linter
  image: golang:latest
  commands:
    - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    - golangci-lint run
  environment:
    GO111MODULE: "off"