---
render_if: drone
---
workspace:
  base: /go
  path: src/{{ .gitserver }}/{{ .organization }}/{{ .name }}

pipeline:
  prerequisites:
    image: "golang:latest"
    pull: true
    commands: 
      - go version
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -vendor-only
    environment:
      - GO111MODULE=off

  linter:
    image: "golang:latest"
    commands:
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run
    environment:
      - GO111MODULE=off

  test:
    image: "golang:latest"
    commands:
      - go test -cover -failfast ./...
    environment:
      - GO111MODULE=off