name: "Example Projectmpl"
version: "0.1.0"
description: "An example template to show how projectmpl works"
delimiters: ["{{", "}}"]
after:
  - cmd: "git init"
    failure: stop
    echo: "Intialized git repo"
    if: git
  - cmd: "git config core.hooksPath .githooks"
    failure: stop
    echo: "Configured git hooks"
    if: git
  - cmd: 'git commit -a -m "intial commit"'
    echo: "Created initial commit"
    if: git
variables:
  name:
    default: rendered
    prompt: "What's the name of your project?"
    help: "The name of your project"
  description:
    prompt: "Describe your project:"
    help: "This will be written in the README.md file"
  organization:
    help: "Organization or username"
    prompt: "What is your username or organization's name?"
    required: true
  gitserver:
    default: "github.com"
    help: "Git server"
  license:
    values: ["MIT", "Apache License 2.0", "GPL", "LGPL", "WTFPL", ""]
    default: "MIT"
    help: "License to be applied to the project. Select the last option if you don't want a license."
    prompt: "Which license do you want to apply to this project?"
  drone:
    confirm: true
    prompt: "Add a Drone configuration?"
  docker:
    confirm: true
    prompt: "Add a Dockerfile and dockerignore?"
  git:
    confirm: true
    prompt: "Initialize git repo and git hooks ?"
