delimiters: ["[[", "]]"]
name: "Example Projectmpl"
version: "0.1.0"
variables:
  name:
    default: rendered
    help: "Simple string"
  choice:
    values: ["Hello", "World"]
    help: "Used for some things"

